name: Dispatch Sync on File Change

on:
  push:
    paths:
      - "Chores/ruleset/reject.list"
      - "Chores/sgmodule/All-in-One-2.x.sgmodule"

jobs:
  check_and_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check for file changes
        id: check_changes
        run: |
          git diff --quiet HEAD^ HEAD Chores/ruleset/reject.list Chores/sgmodule/All-in-One-2.x.sgmodule || echo "changes_detected=true" >> $GITHUB_ENV

      - name: Trigger repository dispatch in TutuBetterRules
        if: env.changes_detected == 'true'
        env:
          DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
        run: |
          curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
               -H "Authorization: token $DISPATCH_TOKEN" \
               https://api.github.com/repos/bunizao/TutuBetterRules/dispatches \
               -d '{"event_type": "sync_files"}'
