name: Merge sgmodule files with merged sections

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '7,32,57 * * * *' 

jobs:
  merge_files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests pyyaml

      - name: Run merge script
        run: |
          python Chores/engineering/merge.py

      - name: Check output directory
        run: |
          mkdir -p Chores/sgmodule
          mkdir -p Chores/ruleset

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add Chores/sgmodule/All-in-One-2.x.sgmodule Chores/ruleset/reject.list
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update merged All-in-One-2.x.sgmodule and reject list"
            git push
          fi
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
