name: Mirror External JS Resources

on:
  # sgmodule 有新的推送时
  push:
    branches: [main]
    paths: ['Chores/sgmodule/**']
  # 每小时 25 分兜底跑一次
  schedule:
    - cron: '25 * * * *'
  # 手动触发
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: write          # 允许推送
    env:
      MIRROR_RAW:  https://github.com/bunizao/Mirrored/raw/main/Chores/js
      MIRROR_KEY:  github.com/bunizao/Mirrored   # 用于 grep 过滤
    steps:
      - uses: actions/checkout@v3

      - name: Ensure curl installed
        run: sudo apt-get update -qq && sudo apt-get install -y curl

      - name: Collect external JS links
        shell: bash
        run: |
          set -e
          # 抓 .js 外链，排除已是 Mirrored 链接
          grep -RohE 'https?://[^"'\'' \t]+\.js' Chores/sgmodule \
            | grep -v "$MIRROR_KEY" \
            | grep -v "$MIRROR_RAW" \
            | sort -u > external-js.txt || true

          if [ ! -s external-js.txt ]; then
            echo "No external JS links found, nothing to mirror."
            exit 0   # 整个 job 成功结束
          fi

          echo "External links to mirror:"
          cat external-js.txt

      - name: Mirror JS & rewrite links
        shell: bash
        run: |
          set -e
          mkdir -p Chores/js

          while read -r url; do
            [ -z "$url" ] && continue
            file=$(basename "$url")
            echo "Mirroring $url → Chores/js/$file"
            curl -Ls "$url" -o "Chores/js/$file"
            # 替换所有 sgmodule 中的旧链接
            sed -i "s|$url|$MIRROR_RAW/$file|g" Chores/sgmodule/*.sgmodule
          done < external-js.txt

          # 删除临时列表文件，避免被 git 捕获
          rm -f external-js.txt

      - name: Commit & push (if changed)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add Chores/js Chores/sgmodule/*.sgmodule

          # 若工作区完全干净，则跳过提交
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "Mirror external JS resources [skip ci]"
          git push
