name: Mirror Upstream Dev Branches

on:
  schedule:
    - cron: '0,25,50 * * * *'  # Runs every 25 minutes
  workflow_dispatch:

jobs:
  mirror_dev_branches:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Set repository list
        run: |
          REPOS=(
            "NSRingo/WeatherKit"
            "NSRingo/News"
            "NSRingo/Testflight"
            "NSRingo/GeoServices"
            "NSRingo/Siri"
            "NSRingo/TV"
          )
          echo "REPOS<<EOF" >> $GITHUB_ENV
          printf "%s\n" "${REPOS[@]}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Mirror upstream dev branches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          CHANGES_DETECTED=false

          for REPO in ${REPOS[@]}; do
            UPSTREAM_REPO="https://github.com/$REPO.git"
            REMOTE_NAME="${REPO//\//-}"

            echo "Adding upstream repository $REPO as remote $REMOTE_NAME"
            git remote add "$REMOTE_NAME" "$UPSTREAM_REPO"

            echo "Fetching dev branch from $REMOTE_NAME"
            git fetch "$REMOTE_NAME" dev

            echo "Merging $REMOTE_NAME/dev into local dev branch"
            git merge --no-edit --allow-unrelated-histories "$REMOTE_NAME/dev" || true

            git remote remove "$REMOTE_NAME"
          done

          if [[ -n $(git status --porcelain) ]]; then
            echo "Changes detected."
            CHANGES_DETECTED=true
          else
            echo "No changes detected."
          fi

          echo "CHANGES_DETECTED=$CHANGES_DETECTED" >> $GITHUB_ENV

      - name: Commit and push changes to dev branch
        if: env.CHANGES_DETECTED == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE="$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')"
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

          git add .
          git commit -m "Mirror upstream dev branches at $DATE (UTC+8)"
          git push origin dev

      - name: No changes detected
        if: env.CHANGES_DETECTED != 'true'
        run: echo "No changes detected. Workflow will exit without committing."
